FROM balenalib/%%BALENA_ARCH%%-debian:bookworm AS base
LABEL maintainer="https://github.com/ketilmo"

EXPOSE 8754

# renovate: datasource=custom.flightradar24 depName=fr24feed versioning=loose
ENV FR24FEED_VERSION=1.0.46-2
ENV FR24_KEY=
